// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyaDh4kU5rSPBYXV7cXMjrtjeksTn04O0',
    appId: '1:529923550274:web:c13f519ff0d22ef7a991db',
    messagingSenderId: '529923550274',
    projectId: 'flutterdb-8847d',
    authDomain: 'flutterdb-8847d.firebaseapp.com',
    storageBucket: 'flutterdb-8847d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCJR5NPwYF3rmTmrXq_yQUgm1abshMo8',
    appId: '1:529923550274:android:609f8327b2cfc726a991db',
    messagingSenderId: '529923550274',
    projectId: 'flutterdb-8847d',
    storageBucket: 'flutterdb-8847d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVP8Ow8WVJqv1w-R05LxZdkzBh3Su9ncE',
    appId: '1:529923550274:ios:34f96f730eb6fca6a991db',
    messagingSenderId: '529923550274',
    projectId: 'flutterdb-8847d',
    storageBucket: 'flutterdb-8847d.appspot.com',
    iosClientId: '529923550274-f2apqs7b04hs4scva5m2ptbv80qr6650.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIntroduccionFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVP8Ow8WVJqv1w-R05LxZdkzBh3Su9ncE',
    appId: '1:529923550274:ios:34f96f730eb6fca6a991db',
    messagingSenderId: '529923550274',
    projectId: 'flutterdb-8847d',
    storageBucket: 'flutterdb-8847d.appspot.com',
    iosClientId: '529923550274-f2apqs7b04hs4scva5m2ptbv80qr6650.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIntroduccionFirebase',
  );
}
